[package]
name = "verifier_applier_runner"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starknet.workspace = true
thiserror.workspace = true
url.workspace = true
tokio.workspace = true
clap.workspace = true
utils.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
dialoguer.workspace = true
regex.workspace = true
anyhow.workspace = true
prover-sdk.workspace = true
cairo-proof-parser.workspace = true
