[package]
name = "server"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/main.rs"
[dependencies]
axum.workspace = true
cairo-proof-parser.workspace = true
clap.workspace = true
podman.workspace = true
thiserror.workspace = true
utils.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
prefix-hex = "0.7.1"
bytes = "1.4.0"
hex = "0.4.3"
serde_with = "1.6.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
ed25519-dalek ={version = "2.1.1", features = ["rand_core"]} 
rand = "0.8.5"
rand_core = "0.6.4"
surrealdb = { version = "1.4.2", features = ["kv-mem"] }
stark-curve = "0.1.1"
elliptic-curve = "0.13.8"
primeorder = "0.13.6"
sha2="0.10.8"
num-bigint = "0.4.4"
uuid = "1.8.0"