[workspace]
resolver = "2"
members = [ "bin/prover", "crates/podman", "crates/utils" ]

[workspace.package]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
axum = { version = "0.7.5", features = ["http2", "macros", "multipart", "ws"] }
podman ={ path = "crates/podman" }
thiserror = "1.0.59"
utils = { path = "crates/utils" }
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["timeout", "trace"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
