[workspace]
members = ["applier", "provable", "verifier", "verifier_applier"]

[workspace.package]
edition = "2023_10"
version = "0.1.0"

[workspace.dependencies]
cairo_verifier = { git = "https://github.com/cartridge-gg/cairo-verifier", branch = "layout/starknet" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.12.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.24.0" }
starknet = "2.6.3"
