[workspace]
members = ["verifier_applier", "provable", "applier"]

[workspace.package]
edition = "2023_10"
version = "0.1.0"

[workspace.dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.12.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.24.0" }
starknet = "2.6.3"
