[package]
name = "json_generator"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
clap.workspace = true
axum.workspace = true
server.workspace = true
starknet.workspace = true
rand_core.workspace = true
elliptic-curve.workspace = true
primeorder.workspace = true
sha2.workspace = true
tracing-subscriber.workspace = true
serde_with.workspace = true
bytes.workspace = true
tower.workspace = true
dialoguer.workspace = true
proptest.workspace = true
rand.workspace = true
surrealdb.workspace = true
tracing.workspace = true
utils.workspace = true
