[package]
name = "json_generator"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
clap.workspace = true
proptest = "1.4.0"
rand = "0.8.5"
surrealdb = "1.4.2"
axum.workspace = true
rand_core = "0.6.4"
elliptic-curve = "0.13.8"
primeorder = "0.13.6"
sha2="0.10.8"
stark-curve = "0.1.1"
serde_with = "1.6.1"
bytes = "1.4.0"
tower = "0.4.13"
dialoguer= "0.11.0"
server.workspace=true 
