[package]
name = "agreement_version_2_runner"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starknet = "0.10.0"
url = "2.5.0"
thiserror.workspace = true
tokio.workspace = true
clap.workspace = true
utils.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
regex = "1.10.4"
sncast = { git = "https://github.com/neotheprogramist/starknet-foundry", branch = "fix/unlock" }
